#!/usr/bin/env bash

set -e
dir="test_files/gen_tests"

echo "[*] Generating a $dir directory.."
mkdir -p $dir

rm -f test_files/gen_tests/*

echo "[*] Generating test files.."

for i in {0..100}
do
    fortune > $dir/ascii$i.input
done

echo "[*] Running the type tests..."

exitcode=0

for f in $dir/*.input
do
  echo "[+] >>> Testing ${f}..."
  file    "${f}" | sed 's/ASCII text.*/ASCII text/' > "${f}.expected"
  sfile  "${f}" > "${f}.actual"

  if ! diff -u "${f}.expected" "${f}.actual"
  then
    echo "[-] >>> Failed :-(" | lolcat
    exitcode=1
  fi
done
